pipeline {
  agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/zalman29096/metropolia_swp_1_homework.git'
            }
        }
        stage('Build') {
            steps {
                dir('week_5') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
            dir('week_5') {
                sh 'mvn test'
                }
            }
        }
        stage('Publish Test Results') {
                    steps {
                        dir('week_5') {
                            junit '**/target/surefire-reports/*.xml'
                        }
                    }
        }
    }

}
